{
 "title": "Logs",
 "tags": [ "handlingar" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   {
    "name": "env",
    "label": "env",
    "query": "handlingar,tst,qat,handlingar-preview"
   }
  ]
 },
 "panels": [
  {
   "title": "Rails 5xx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=~\"$env\", app=\"alaveteli\"} |~ \"Completed 5[0-9]{2}\""
    }
   ]
  },
  {
   "title": "Sidekiq errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=~\"$env\", app=\"alaveteli-sidekiq\"} |~ \"(?i)(error|exception)\""
    }
   ]
  },
  {
   "title": "cert-manager errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=\"cert-manager\"} |~ \"(?i)error\""
    }
   ]
  }
 ]
}